from __future__ import annotations

import shlex
from pathlib import Path

from ddpt.anonymize import plan_anonymization_actions
from ddpt.models import DcmodifyPlanItem, DcmodifyPlanReport
from ddpt.utils import ensure_parent

UID_SHORTCUTS = {
    "StudyInstanceUID": ("-gst", "generate new Study Instance UID"),
    "SeriesInstanceUID": ("-gse", "generate new Series Instance UID"),
    "SOPInstanceUID": ("-gin", "generate new SOP Instance UID"),
}


def build_dcmodify_plan(
    input_path: Path,
    profile: str = "dental-basic",
) -> DcmodifyPlanReport:
    audit = plan_anonymization_actions(input_path, profile)
    input_text = str(input_path.resolve())
    items: list[DcmodifyPlanItem] = []

    for order, action in enumerate(audit.actions, start=1):
        items.append(_item_from_action(order, action, input_text))

    if audit.private_tags_removed:
        items.append(
            DcmodifyPlanItem(
                order=len(items) + 1,
                keyword="PrivateTags",
                tag="private",
                profile_action="remove_private_tags",
                dcmodify_action="erase-private",
                option="-ep",
                argument="",
                command=shlex.join(["dcmodify", "-ep", input_text]),
                value_preview="",
                note="Erase private DICOM tags; review vendor-specific requirements first.",
            )
        )

    return DcmodifyPlanReport(
        input_path=input_text,
        profile=audit.profile,
        total_operations=len(items),
        modify_operations=sum(1 for item in items if item.dcmodify_action == "modify"),
        uid_operations=sum(1 for item in items if item.dcmodify_action == "generate-uid"),
        private_tag_operations=sum(
            1 for item in items if item.dcmodify_action == "erase-private"
        ),
        commands=[item.command for item in items],
        items=items,
        note=(
            "Review-only DCMTK dcmodify-style plan. Commands are not executed by "
            "the toolkit, and dcmodify edits files in place unless you manage "
            "copies/backups yourself."
        ),
    )


def write_dcmodify_script(path: Path, report: DcmodifyPlanReport) -> None:
    ensure_parent(path)
    lines = [
        "#!/usr/bin/env sh",
        "set -eu",
        "",
        "# Generated by Dental DICOM Privacy Toolkit.",
        "# Review before running. dcmodify edits DICOM files in place.",
        f"# Input: {report.input_path}",
        f"# Profile: {report.profile}",
        "",
    ]
    lines.extend(report.commands)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _item_from_action(order: int, action, input_text: str) -> DcmodifyPlanItem:
    if action.action == "regenerate_uid":
        option, note = UID_SHORTCUTS.get(
            action.keyword,
            (
                "-m",
                "No dcmodify UID shortcut is available; replace the placeholder UID.",
            ),
        )
        if action.keyword in UID_SHORTCUTS:
            argument = ""
            command = shlex.join(["dcmodify", option, input_text])
        else:
            argument = f"{action.tag}=<generated-uid>"
            command = shlex.join(["dcmodify", "-imt", "-m", argument, input_text])
        return DcmodifyPlanItem(
            order=order,
            keyword=action.keyword,
            tag=action.tag,
            profile_action=action.action,
            dcmodify_action="generate-uid",
            option=option,
            argument=argument,
            command=command,
            value_preview="<generated-uid>",
            note=note,
        )

    value = "" if action.action == "blank" else action.after
    argument = f"{action.tag}={value}"
    return DcmodifyPlanItem(
        order=order,
        keyword=action.keyword,
        tag=action.tag,
        profile_action=action.action,
        dcmodify_action="modify",
        option="-m",
        argument=argument,
        command=shlex.join(["dcmodify", "-imt", "-m", argument, input_text]),
        value_preview=value,
        note="Modify or insert the DICOM tag value according to the selected profile.",
    )
