from __future__ import annotations

import json
import shlex
from html import escape
from pathlib import Path

from ddpt.anonymize import plan_anonymization_actions
from ddpt.dcmodify_plan import build_dcmodify_plan, write_dcmodify_script
from ddpt.models import (
    AnonymizationAction,
    ReferenceToolArtifact,
    ReferenceToolExportReport,
    ReferenceToolMappingItem,
)
from ddpt.orthanc_plan import build_orthanc_anonymize_plan
from ddpt.reports import model_to_dict, write_dcmodify_plan_html, write_orthanc_plan_html
from ddpt.utils import write_json

BOUNDARY_NOTES = [
    "Reference-tool export pack is review-only; no external tool is executed.",
    "Generated dcmodify commands can edit DICOM files in place if a user runs them manually.",
    "Generated Orthanc curl commands are examples only; the toolkit does not contact Orthanc.",
    "Generated RSNA CTP-style files are migration notes, not a guaranteed drop-in CTP install.",
    "Generated pydicom script is for synthetic/local review and must be audited before reuse.",
]


def build_reference_tool_export_pack(
    input_path: Path,
    output_dir: Path,
    profile: str = "dental-basic",
    resource_id: str = "<orthanc-resource-id>",
    orthanc_base_url: str = "http://localhost:8042",
) -> ReferenceToolExportReport:
    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    action_plan = plan_anonymization_actions(input_path, profile)
    artifacts: list[ReferenceToolArtifact] = []

    dcmtk_dir = output_dir / "dcmtk"
    dcmodify_report = build_dcmodify_plan(input_path, profile=profile)
    dcmodify_json = dcmtk_dir / "dcmodify-plan.json"
    dcmodify_html = dcmtk_dir / "dcmodify-plan.html"
    dcmodify_script = dcmtk_dir / "dcmodify-plan.sh"
    write_json(dcmodify_json, model_to_dict(dcmodify_report))
    write_dcmodify_plan_html(dcmodify_html, dcmodify_report)
    write_dcmodify_script(dcmodify_script, dcmodify_report)
    dcmodify_script.chmod(0o755)
    artifacts.extend(
        [
            _artifact("DCMTK dcmodify", dcmodify_json, "json", "dcmodify operation plan"),
            _artifact("DCMTK dcmodify", dcmodify_html, "html", "dcmodify review report"),
            _artifact("DCMTK dcmodify", dcmodify_script, "shell", "review shell script"),
        ]
    )

    orthanc_dir = output_dir / "orthanc"
    orthanc_report = build_orthanc_anonymize_plan(
        input_path,
        profile=profile,
        resource_id=resource_id,
        orthanc_base_url=orthanc_base_url,
    )
    orthanc_json = orthanc_dir / "orthanc-plan.json"
    orthanc_html = orthanc_dir / "orthanc-plan.html"
    orthanc_payload = orthanc_dir / "orthanc-payload.json"
    orthanc_curl = orthanc_dir / "orthanc-anonymize.sh"
    write_json(orthanc_json, model_to_dict(orthanc_report))
    write_orthanc_plan_html(orthanc_html, orthanc_report)
    write_json(orthanc_payload, orthanc_report.payload)
    _write_executable_script(
        orthanc_curl,
        [
            "# Generated by Dental DICOM Privacy Toolkit.",
            "# Review before running. This command sends a request to Orthanc.",
            *orthanc_report.curl_commands,
        ],
    )
    artifacts.extend(
        [
            _artifact("Orthanc", orthanc_json, "json", "Orthanc anonymization plan"),
            _artifact("Orthanc", orthanc_html, "html", "Orthanc review report"),
            _artifact("Orthanc", orthanc_payload, "json", "Orthanc REST payload preview"),
            _artifact("Orthanc", orthanc_curl, "shell", "review curl command"),
        ]
    )

    ctp_dir = output_dir / "rsna-ctp"
    ctp_dir.mkdir(parents=True, exist_ok=True)
    ctp_script = ctp_dir / "ctp-anonymizer.script"
    ctp_pipeline = ctp_dir / "ctp-style-pipeline.xml"
    ctp_readme = ctp_dir / "README.md"
    ctp_script.write_text(_ctp_script_text(action_plan.actions), encoding="utf-8")
    ctp_pipeline.write_text(_ctp_pipeline_text(profile), encoding="utf-8")
    ctp_readme.write_text(_ctp_readme_text(profile), encoding="utf-8")
    artifacts.extend(
        [
            _artifact("RSNA CTP", ctp_script, "text", "CTP-style anonymizer script"),
            _artifact("RSNA CTP", ctp_pipeline, "xml", "CTP-style pipeline sketch"),
            _artifact("RSNA CTP", ctp_readme, "markdown", "CTP migration notes"),
        ]
    )

    pydicom_dir = output_dir / "pydicom"
    pydicom_dir.mkdir(parents=True, exist_ok=True)
    pydicom_script = pydicom_dir / "pydicom-profile-anonymizer.py"
    pydicom_readme = pydicom_dir / "README.md"
    pydicom_script.write_text(_pydicom_script_text(action_plan.actions), encoding="utf-8")
    pydicom_script.chmod(0o755)
    pydicom_readme.write_text(_pydicom_readme_text(profile), encoding="utf-8")
    artifacts.extend(
        [
            _artifact("pydicom", pydicom_script, "python", "profile-derived pydicom script"),
            _artifact("pydicom", pydicom_readme, "markdown", "pydicom review notes"),
        ]
    )

    index_readme = output_dir / "README.md"
    index_readme.write_text(_index_readme_text(profile, artifacts), encoding="utf-8")
    artifacts.append(
        _artifact("Reference export pack", index_readme, "markdown", "pack index")
    )

    mapping = _build_mapping(action_plan.actions, dcmodify_report.commands, orthanc_report.items)
    passed = all(Path(item.path).exists() for item in artifacts)
    return ReferenceToolExportReport(
        input_path=str(input_path.resolve()),
        profile=action_plan.profile,
        output_dir=str(output_dir),
        passed=passed,
        total_operations=len(mapping),
        tools=[
            "DCMTK dcmodify",
            "Orthanc",
            "RSNA CTP",
            "pydicom",
        ],
        artifacts=artifacts,
        mapping=mapping,
        boundary_notes=BOUNDARY_NOTES,
    )


def _artifact(
    tool: str,
    path: Path,
    format_name: str,
    description: str,
) -> ReferenceToolArtifact:
    return ReferenceToolArtifact(
        tool=tool,
        path=str(path),
        format=format_name,
        description=description,
    )


def _build_mapping(
    actions: list[AnonymizationAction],
    dcmodify_commands: list[str],
    orthanc_items,
) -> list[ReferenceToolMappingItem]:
    orthanc_by_keyword = {item.keyword: item for item in orthanc_items}
    items: list[ReferenceToolMappingItem] = []
    for order, action in enumerate(actions, start=1):
        orthanc_item = orthanc_by_keyword.get(action.keyword)
        orthanc_mapping = (
            f"{orthanc_item.orthanc_section}:{orthanc_item.orthanc_key}"
            if orthanc_item
            else "review-only"
        )
        items.append(
            ReferenceToolMappingItem(
                order=order,
                keyword=action.keyword,
                tag=action.tag,
                profile_action=action.action,
                dcmtk_command=dcmodify_commands[order - 1]
                if order - 1 < len(dcmodify_commands)
                else "",
                orthanc_mapping=orthanc_mapping,
                ctp_script_line=_ctp_line(action),
                pydicom_statement=_pydicom_statement(action),
                note=(
                    "One dental YAML profile action is translated into "
                    "reference-tool review artifacts."
                ),
            )
        )
    return items


def _ctp_script_text(actions: list[AnonymizationAction]) -> str:
    lines = [
        "# Dental DICOM Privacy Toolkit",
        "# RSNA CTP-style anonymizer script for review and migration planning.",
        "# This file is not guaranteed to be a drop-in CTP script.",
        "# Use only with synthetic or explicitly approved test DICOM files.",
        "",
        "remove_private_groups = true",
    ]
    lines.extend(_ctp_line(action) for action in actions)
    return "\n".join(lines) + "\n"


def _ctp_line(action: AnonymizationAction) -> str:
    if action.action == "regenerate_uid":
        return f"set {action.keyword} = <new-uid>"
    if action.action == "blank":
        return f"set {action.keyword} ="
    if action.action == "date_shift":
        return f"set {action.keyword} = <shifted-date>"
    return f"set {action.keyword} = {action.after}"


def _ctp_pipeline_text(profile: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        "<!-- Review-only RSNA CTP-style pipeline sketch generated by DDPT. -->\n"
        "<Pipeline name=\"DDPTDentalPrivacyReviewOnly\">\n"
        "  <ImportService class=\"org.rsna.ctp.stdstages.FileImportService\" root=\"input\" />\n"
        "  <DicomAnonymizer\n"
        "      class=\"org.rsna.ctp.stdstages.DicomAnonymizer\"\n"
        "      profile=\""
        + escape(profile)
        + "\"\n"
        "      script=\"ctp-anonymizer.script\" />\n"
        "  <ExportService class=\"org.rsna.ctp.stdstages.FileStorageService\" root=\"output\" />\n"
        "</Pipeline>\n"
    )


def _ctp_readme_text(profile: str) -> str:
    return f"""# RSNA CTP-style Export Notes

Profile: `{profile}`

These files are generated for migration review. They preserve the DDPT profile
decisions in a CTP-like shape so a CTP operator can compare stages, anonymizer
rules, and safety boundaries before writing a real CTP configuration.

Do not place real patient DICOM files in this public export folder.
"""


def _pydicom_script_text(actions: list[AnonymizationAction]) -> str:
    actions_json = json.dumps(
        [action.model_dump(mode="json") for action in actions],
        indent=2,
        ensure_ascii=False,
    )
    return f'''#!/usr/bin/env python3
"""Profile-derived pydicom anonymizer generated by DDPT.

Review before use. This script is intended for synthetic/local tests and does
not replace DDPT validation, pixel review, or legal/privacy review.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pydicom
from pydicom.uid import generate_uid

ACTIONS = {actions_json}


def apply_profile(dataset):
    for item in ACTIONS:
        keyword = item["keyword"]
        action = item["action"]
        if action == "regenerate_uid":
            value = generate_uid()
        elif action == "date_shift":
            value = item["after"]
        else:
            value = item["after"]
        setattr(dataset, keyword, value)

    dataset.remove_private_tags()
    if hasattr(dataset, "SOPInstanceUID") and getattr(dataset, "file_meta", None):
        dataset.file_meta.MediaStorageSOPInstanceUID = dataset.SOPInstanceUID
    return dataset


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("--out", required=True, type=Path)
    args = parser.parse_args()

    dataset = pydicom.dcmread(args.input)
    apply_profile(dataset)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    dataset.save_as(args.out)


if __name__ == "__main__":
    main()
'''


def _pydicom_statement(action: AnonymizationAction) -> str:
    if action.action == "regenerate_uid":
        value = "generate_uid()"
    else:
        value = repr(action.after)
    return f"setattr(dataset, {action.keyword!r}, {value})"


def _pydicom_readme_text(profile: str) -> str:
    command = shlex.join(
        [
            "python",
            "pydicom-profile-anonymizer.py",
            "input.synthetic.dcm",
            "--out",
            "output.synthetic.dcm",
        ]
    )
    return f"""# pydicom Export Notes

Profile: `{profile}`

The generated Python script shows how DDPT profile actions map to pydicom-style
metadata edits. It is intentionally small so researchers can inspect the logic.

Example:

```sh
{command}
```

Run DDPT validation and comparison reports after using any exported script.
"""


def _index_readme_text(profile: str, artifacts: list[ReferenceToolArtifact]) -> str:
    lines = [
        "# Reference Tool Export Pack",
        "",
        f"Profile: `{profile}`",
        "",
        "Synthetic-data review package for comparing DDPT profile behavior with",
        "DCMTK dcmodify, Orthanc, RSNA CTP-style pipeline thinking, and pydicom.",
        "",
        "## Artifacts",
        "",
    ]
    for artifact in artifacts:
        lines.append(
            f"- `{artifact.path}` - {artifact.tool}, {artifact.format}: "
            f"{artifact.description}"
        )
    lines.extend(
        [
            "",
            "## Safety",
            "",
            "- Review-only: generated external-tool commands are not executed by DDPT.",
            "- Use synthetic or explicitly approved test DICOM files only.",
            "- Verify any generated config against the exact target tool version.",
        ]
    )
    return "\n".join(lines) + "\n"


def _write_executable_script(path: Path, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("#!/usr/bin/env sh\nset -eu\n\n" + "\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o755)
